class stolyScene extends appScene
    constructor: () ->
        super
        @gp_load = new gpLoadStory()
        @loadFile = []
        @cue = {}
        @panorama = ''
    resetScene:()->
        @gp_panorama = new gpStoryPanorama(@panorama)
        @gp_sentence = new gpStorySentence()
        @gp_object = new gpStoryObject()
        @gp_object_up = new gpStoryObjectUp()
        @addChild(@gp_panorama)
        @addChild(@gp_sentence)
        @addChild(@gp_object)
        @addChild(@gp_object_up)
    startScene:()->
        @addChild(@gp_load)
        game.multiLoad(@loadFile)
    startSceneExe:()->
        @removeChild(@gp_load)
        @resetScene()
        @cueSet(@cue)
    faceSet:(face, x=0, y=0, move=false)->
        if !move
            @gp_object.addChild(face)
        face.x =  @gp_panorama.panorama.x + x
        face.y = @gp_panorama.panorama.y + y
    unsetEmote:()->
        @gp_object_up.emote.unset()
    panoramaChange:(panorama)->
        @panorama = panorama
        @gp_panorama.panoramaChange(@panorama)
    panoramaChangeRect:(color='black')->
        @gp_panorama.panoramaChangeRect(color)
    panoramaHide:()->
        @gp_panorama.panorama.hide()
    panoramaShow:()->
        @gp_panorama.panorama.show()
    ###
    タイムラインのキューに秒数を累積しながらセット
    ###
    cueSet:(cue)->
        ret = {}
        total = 0
        for num, func of cue
            ret[Math.floor(total * game.fps)] = func[1]
            total += func[0]
        @tl.cue(ret)
    addLoadFile:(files)->
        init = ['images/emote.png', 'sounds/emote1.mp3', 'sounds/emote2.mp3', 'sounds/emote3.mp3', 'sounds/emote4.mp3']
        files = files.concat(init)
        @loadFile = files
    bgmStop:()->
        if @gp_object.bgm != null
            game.bgmStop(@gp_object.bgm)
            if game.main_scene != undefined && game.main_scene.bgm != undefined
                game.nowPlayBgm = game.main_scene.bgm
    #http://wise9.github.io/enchant.js/doc/core/ja/symbols/enchant.Timeline.html
    #http://r.jsgames.jp/games/1687/
    ###
    必要な素材は必ずresetScene()で生成するクラス内で呼び出す
    'back_gakko', 'back_busitu', 'back_stage', 'back_roka', 'back_okujou', 'back_kanda'
    'face_honoka','face_kotori', 'face_umi', 'face_maki', 'face_rin', 'face_hanayo', 'face_nico', 'face_nozomi', 'face_eli'
    アクション
    tateShake() tateShake2() rotateShake() randomShake() scale() scaleIn() scaleOut()
    感情アイコン
    'bikkuri':0, 'hatena':1,'onpu':2, 'heart':3, 'ase':4, 'gabin':5, 'ten':6
    文字の表示時間
    最低4秒、文字数／10秒＋小数点以下は四捨五入、カンマが3つ以上で1秒延長
    ###
    testStart:()->
        @panorama = 'back_busitu'
        @addLoadFile(['images/back_busitu.png', 'images/face_honoka.png', 'images/face_kotori.png',
            'images/face_umi.png', 'images/face_maki.png', 'images/face_rin.png', 'images/face_hanayo.png',
            'images/face_nico.png', 'images/face_nozomi.png', 'images/face_eli.png'
        ])
        @cue = [
            [
                1,
                =>
                    @faceSet(@gp_object.rin, 180, 0)
                    @faceSet(@gp_object.hanayo, 50, 0)
                    @faceSet(@gp_object.maki, 300, 0)
                    @faceSet(@gp_object.honoka, 180, 90)
                    @faceSet(@gp_object.kotori, 300, 90)
                    @faceSet(@gp_object.umi, 50, 90)
                    @faceSet(@gp_object.nozomi, 170, 190)
                    @faceSet(@gp_object.nico, 40, 190)
                    @faceSet(@gp_object.eli, 300, 190)
                    @gp_object.rin.scaleChange(0.7)
                    @gp_object.hanayo.scaleChange(0.7)
                    @gp_object.maki.scaleChange(0.7)
                    @gp_object.honoka.scaleChange(0.7)
                    @gp_object.kotori.scaleChange(0.7)
                    @gp_object.umi.scaleChange(0.7)
                    @gp_object.nozomi.scaleChange(0.7)
                    @gp_object.nico.scaleChange(0.7)
                    @gp_object.eli.scaleChange(0.7)
            ],
            [
                2,
                =>
                    @gp_object.rin.emoteSize = 0.7
                    @gp_object.rin.rotateShake()
                    @gp_object.rin.setEmote('onpu')
            ],
            [
                1,
                =>
                    @unsetEmote()
            ],
            [
                0,
                =>
                    #game.endStory()
            ]
        ]
        @startScene()
    opStart:()->
        @panorama = 'back_gakko'
        @addLoadFile([
            'images/back_gakko.png', 'images/back_roka.png', 'images/face_honoka.png', 'images/face_kotori.png', 'images/face_umi.png',
            'sounds/bgm/bgm_sakusen.mp3'
        ])
        @cue = [
            [
                5,
                =>
                    @gp_sentence.txtSet(
                        'ここは某音ノ木坂学院、<br>廃校が決まったあと、突然穂乃果が<br>スクールアイドルを始めると言い出した'
                    )
            ],
            [
                1,
                =>
                    @gp_sentence.txtEnd()
                    @panoramaChange('back_roka')
            ]
            [
                1,
                =>
                    @gp_object.playBgm('bgm_sakusen')
                    @faceSet(@gp_object.honoka, 170, 90)
                    @faceSet(@gp_object.kotori, 20, 95)
                    @faceSet(@gp_object.umi, 320, 85)
            ],
            [
                4,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.honoka.setEmote('bikkuri')
                    @gp_object.honoka.rotateShake()
                    @gp_sentence.txtSet(
                        '穂乃果<br>海未ちゃん、,ことりちゃん、,<br>スクールアイドルを始めるよ！'
                    )
            ],
            [
                8,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.kotori.setEmote('hatena')
                    @gp_object.kotori.rotateShake()
                    @gp_sentence.txtSet(
                        'ことり<br>スクールアイドルってあの？<br>学生たちでアイドルをやってる、,<br>ネットでPVなんかも公開してて、,<br>全国に有名なスクールアイドルもいる'
                    )
            ],
            [
                6,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.honoka.setEmote('bikkuri')
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtSet(
                        '穂乃果<br>そう、それだよ！,スクールアイドル！,<br>スクールアイドルを始めて有名になれば,<br>廃校を阻止することができるよ！'
                    )
            ],
            [
                6,
                =>
                    @gp_sentence.txtEnd()
                    @unsetEmote()
                    @gp_object.umi.tateShake()
                    @gp_sentence.txtSet(
                        '海未<br>穂乃果、,簡単にスクールアイドルを<br>始めるとは言ってもですね、,<br>廃校を阻止するだけ有名になるには、'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.umi.rotateShake()
                    @gp_sentence.txtSet(
                        '海未<br>歌や衣装、,ダンスにPV撮影等、,<br>それなりにプロに匹敵するだけのものが<br>必要になるんですよ。'
                    )
            ],
            [
                4,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.umi.tateShake()
                    @gp_sentence.txtSet(
                        '海未<br>私達３人だけでは到底<br>それだけの物は用意できません。'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.honoka.setEmote('onpu')
                    @gp_object.honoka.rotateShake()
                    @gp_sentence.txtSet(
                        '穂乃果<br>それなら大丈夫だよ、,海未ちゃん！,<br>お金の力があればなんとかなるよ！'
                    )
            ],
            [
                6,
                =>
                    @gp_sentence.txtEnd()
                    @unsetEmote()
                    @gp_object.honoka.rotateShake()
                    @gp_sentence.txtSet(
                        '穂乃果<br>プロの作詞者、,プロの作曲者、,<br>衣装や舞台装置、,<br>他にもいっぱいプロのスタッフたちを,<br>お金で雇えば、'
                    )
            ],
            [
                3,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtSet(
                        '穂乃果<br>素敵なPVが撮影できるよ！'
                    )
            ],
            [
                7,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.umi.setEmote('ase')
                    @gp_object.umi.tateShake()
                    @gp_sentence.txtSet(
                        '海未<br>何を他力本願なことを<br>言っているのですか、,<br>それに、,仮にそうするとしても、,<br>そんなお金、,どこにあるというのですか、'
                    )
            ],
            [
                3,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.umi.setEmote('bikkuri')
                    @gp_object.umi.rotateShake()
                    @gp_sentence.txtSet(
                        '海未<br>簡単に見積もっても,<br>『１００万円』程は必要ですよ！'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.honoka.setEmote('onpu')
                    @gp_object.honoka.rotateShake()
                    @gp_sentence.txtSet(
                        '穂乃果<br>なーんだ、,『１００万円』か、,<br>そんなの簡単じゃん！,<br>スロットマシンで稼げばいいじゃない！'
                    )
            ],
            [
                3,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.umi.setEmote('ten')
            ],
            [
                4,
                =>
                    @unsetEmote()
                    @gp_object.umi.scale()
                    @gp_sentence.txtSet(
                        '海未<br>ちょっと穂乃果、,<br>それ本気で言っているのですか！？'
                    )
            ],
            [
                4,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.kotori.scale()
                    @gp_sentence.txtSet(
                        'ことり<br>そうだよホノカチャン！,<br>さすがにギャンブルは無茶だよ！'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.honoka.setEmote('onpu')
                    @gp_object.honoka.scaleIn()
                    @gp_sentence.txtSet(
                        '穂乃果<br>ダイジョーブ、,ダイジョーブ！<br>ここに穂乃果のなけなしのお小遣い,<br>『１００円』があるから、'
                    )
            ],
            [
                2,
                =>
                    @gp_sentence.txtEnd()
                    @unsetEmote()
                    @gp_object.honoka.tateShake()
                    @gp_sentence.txtSet(
                        '穂乃果<br>これを元手に頑張ってね！,<br>それじゃあ任せたよ！,ことりちゃん！'
                    )
            ],
            [
                3,
                =>
                    @gp_object.honoka.scaleOut()
            ],
            [
                3,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.kotori.setEmote('ten')
            ],
            [
                6,
                =>

                    @gp_object.kotori.setEmote('gabin')
                    @gp_object.kotori.randomShake()
                    @gp_sentence.txtSet(
                        'ことり<br>『１００円』！？,<br>ちょっとホノカチャン、,無理だよぉ！,<br>それに何で私！？'
                    )
            ],
            [
                4,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.honoka.setEmote('onpu')
                    @gp_object.honoka.rotateShake()
                    @gp_sentence.txtSet(
                        '穂乃果<br>ことりちゃん、,大好き！,<br>頑張ってね！'
                    )
            ],
            [
                2,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.kotori.setEmote('heart')
            ],
            [
                4,
                =>
                    @gp_object.kotori.tateShake2()
                    @gp_sentence.txtSet(
                        'ことり<br>うん、,ホノカチャン！,<br>わたし頑張る！'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @unsetEmote()
                    @gp_object.umi.scale()
                    @gp_sentence.txtSet(
                        '海未<br>穂乃果！,いいかげんにしなさい！,<br>ことりも、,、,無茶です！'
                    )
            ],
            [
                4,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.honoka.setEmote('onpu')
                    @gp_object.honoka.rotateShake()
                    @gp_sentence.txtSet(
                        '穂乃果<br>海未ちゃんも,だーいすき！！'
                    )
            ],
            [
                2,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.umi.setEmote('heart')
            ],
            [
                4,
                =>
                    @gp_object.umi.tateShake2()
                    @gp_sentence.txtSet(
                        '海未<br>まったく、,仕方ないですね、,<br>ことり、,頼みましたよ。'
                    )
            ],
            [
                6,
                =>
                    @gp_sentence.txtEnd()
                    @unsetEmote()
                    @gp_object.kotori.tateShake2()
                    @gp_sentence.txtSet(
                        'ことり<br>うん！,それじゃあ私に任せてね！,<br>『１００万円』稼いでくるから！'
                    )
            ],
            [
                0,
                =>
                    @gp_sentence.txtEnd()
                    game.endStory()
            ]
        ]
        @startScene()
    story2ndStart:()->
        @panorama = 'back_busitu'
        @addLoadFile([
            'images/back_busitu.png', 'images/face_maki.png', 'images/face_rin.png', 'images/face_hanayo.png',
            'sounds/bgm/bgm_setumei.mp3'
        ])
        @cue = [
            [
                5,
                =>
                    @gp_sentence.txtSet(
                        'なんやかんやあって、<br>穂乃果たちはメンバーを９人集め、<br>スクールアイドルμ’ｓを結成。'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことりが稼いだ１００万円で作った<br>「僕らのLIVE君とのLIFE」のPVは<br>好調に再生数を稼ぎ'
                    )
            ],
            [
                4,
                =>
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'μ’ｓは着々と<br>知名度を上げていくのであった。'
                    )
            ],
            [
                1,
                =>
                    @gp_object.playBgm('bgm_setumei')
                    @gp_sentence.txtEnd()
                    @faceSet(@gp_object.rin, 170, 90)
                    @faceSet(@gp_object.hanayo, 20, 90)
                    @faceSet(@gp_object.maki, 320, 90)
            ],
            [
                5,
                =>
                    @gp_object.hanayo.setEmote('bikkuri')
                    @gp_sentence.txtEnd()
                    @gp_object.hanayo.rotateShake()
                    @gp_sentence.txtSet(
                        '花陽<br>大変です！大変です！,<br>ラブライブです！,<br>ラブライブが始まりました！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.rin.setEmote('hatena')
                    @gp_sentence.txtEnd()
                    @gp_object.rin.rotateShake()
                    @gp_sentence.txtSet(
                        '凛<br>ラブライブ！,<br>ラブライブって何だにゃ？,<br>そういうラーメンがあるのかにゃ？'
                    )
            ],
            [
                5,
                =>
                    @gp_object.hanayo.setEmote('bikkuri')
                    @gp_sentence.txtEnd()
                    @gp_object.hanayo.rotateShake()
                    @gp_sentence.txtSet(
                        '花陽<br>違います！,<br>ラブライブといえば,<br>スクールアイドルの甲子園！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.hanayo.setEmote('bikkuri')
                    @gp_sentence.txtEnd()
                    @gp_object.hanayo.tateShake2()
                    @gp_sentence.txtSet(
                        '花陽<br>優勝したらそれはそれは凄い<br>大人気アイドルになれるんです！'
                    )
            ],
            [
                4,
                =>
                    @unsetEmote()
                    @gp_sentence.txtEnd()
                    @gp_object.hanayo.tateShake()
                    @gp_sentence.txtSet(
                        '花陽<br>それに、,<br>学校も廃校にならずに済みます！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.rin.setEmote('onpu')
                    @gp_sentence.txtEnd()
                    @gp_object.rin.tateShake2()
                    @gp_sentence.txtSet(
                        '凛<br>それじゃあ、,<br>今度も前みたいに<br>お金の力でなんとかするにゃ！'
                    )
            ],
            [
                6,
                =>
                    @unsetEmote()
                    @gp_sentence.txtEnd()
                    @gp_object.maki.rotateShake()
                    @gp_sentence.txtSet(
                        '真姫<br>そうね、,ラブライブで優勝する為には、,<br>それ相応に必要な人気、,<br>知名度が必要になるから、'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.maki.rotateShake()
                    @gp_sentence.txtSet(
                        '真姫<br>ラブライブまでに人気を集めるために,<br>曲やPVも、,もっとたくさん<br>必要になってくるわ！'
                    )
            ],
            [
                6,
                =>
                    @gp_object.hanayo.setEmote('bikkuri')
                    @gp_sentence.txtEnd()
                    @gp_object.hanayo.tateShake2()
                    @gp_sentence.txtSet(
                        '花陽<br>そうです！<br>それにPVのクオリティも<br>学校で撮影した「ぼららら」程度の<br>クオリティではダメです！'
                    )
            ],
            [
                4,
                =>
                    @unsetEmote()
                    @gp_sentence.txtEnd()
                    @gp_object.hanayo.tateShake()
                    @gp_sentence.txtSet(
                        '花陽<br>もっとセットも演出も、,<br>もっともっと豪華にしていかないと！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.hanayo.setEmote('bikkuri')
                    @gp_sentence.txtEnd()
                    @gp_object.hanayo.scale()
                    @gp_sentence.txtSet(
                        '花陽<br>その費用を算出してみたら、,<br>『１億円』は必要になるんです！'
                    )
            ],
            [
                4,
                =>
                    @gp_object.rin.setEmote('onpu')
                    @gp_sentence.txtEnd()
                    @gp_object.rin.tateShake2()
                    @gp_sentence.txtSet(
                        '凛<br>真姫ちゃんのお小遣いがあれば<br>楽勝にゃ！'
                    )
            ],
            [
                5,
                =>
                    @unsetEmote()
                    @gp_sentence.txtEnd()
                    @gp_object.maki.rotateShake()
                    @gp_sentence.txtSet(
                        '真姫<br>そうね、,実はそのことなんだけど、,<br>あのスロットマシンから出てくるお金'
                    )
            ],
            [
                4,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.maki.rotateShake()
                    @gp_sentence.txtSet(
                        '真姫<br>全部私のお小遣いから<br>出しているのよ。'
                    )
            ],
            [
                3,
                =>
                    @gp_object.rin.setEmote('ten')
                    @gp_sentence.txtEnd()
            ],
            [
                4,
                =>
                    @unsetEmote()
                    @gp_sentence.txtEnd()
                    @gp_object.rin.rotateShake()
                    @gp_sentence.txtSet(
                        '凛<br>何だ、,そんなことだったのかにゃ。'
                    )
            ],
            [
                5,
                =>
                    @gp_object.rin.setEmote('onpu')
                    @gp_sentence.txtEnd()
                    @gp_object.rin.tateShake()
                    @gp_sentence.txtSet(
                        '凛<br>それじゃあ、,<br>またことりちゃんに<br>頑張ってもらうしかないにゃ！'
                    )
            ],
            [
                4,
                =>
                    @gp_object.maki.setEmote('onpu')
                    @gp_sentence.txtEnd()
                    @gp_object.maki.tateShake()
                    @gp_sentence.txtSet(
                        '真姫<br>そうね、,散水。'
                    )
            ],
            [
                3,
                =>
                    @gp_object.hanayo.setEmote('ten')
                    @gp_sentence.txtEnd()
            ],
            [
                6,
                =>
                    @gp_object.hanayo.setEmote('ase')
                    @gp_sentence.txtEnd()
                    @gp_object.hanayo.randomShake()
                    @gp_sentence.txtSet(
                        '花陽<br>ちょっと待ってください、,<br>話がおかしいです！,<br>それならスロットマシンなんか<br>やらなくても'
                    )
            ],
            [
                4,
                =>
                    @unsetEmote()
                    @gp_sentence.txtEnd()
                    @gp_object.hanayo.tateShake()
                    @gp_sentence.txtSet(
                        '花陽<br>真姫ちゃんが直接<br>お金を出してくれれば・・・'
                    )
            ],
            [
                3,
                =>
                    @gp_object.rin.setEmote('ten')
                    @gp_sentence.txtEnd()
            ],
            [
                6,
                =>
                    @unsetEmote()
                    @gp_sentence.txtEnd()
                    @gp_object.rin.tateShake2()
                    @gp_sentence.txtSet(
                        '凛<br>とにかくことりちゃんに<br>頑張って『１億円』<br>稼いできて貰うにゃ！'
                    )
            ],
            [
                0,
                =>
                    @gp_sentence.txtEnd()
                    game.endStory()
            ]
        ]
        @startScene()
    story3rdStart:()->
        @panorama = 'back_okujou'
        @addLoadFile([
            'images/back_okujou.png', 'images/face_honoka.png', 'images/face_kotori.png', 'images/face_umi.png',
            'sounds/bgm/bgm_n.mp3'
            ])
        @cue = [
            [
                5,
                =>
                    @gp_sentence.txtSet(
                        '予算を大漁にぶちこんだ<br>圧倒的なPVの数々が功を奏し、<br>μ’ｓは一躍人気者に。'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '音ノ木坂学園の入学希望者も増え、<br>廃校にならずに済んだのであった。'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'しかし、その後も何かと一悶着あり、<br>一度はラブライブの出場を<br>辞退したのであったが'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'なんやかんやで、<br>何故か2回目のラブライブが開催され、<br>再びエントリーしたのであった。'
                    )
            ],
            [
                2,
                =>
                    @gp_object.playBgm('bgm_n')
                    @gp_sentence.txtEnd()
                    @faceSet(@gp_object.honoka, 170, 90)
                    @faceSet(@gp_object.kotori, 20, 95)
                    @faceSet(@gp_object.umi, 320, 85)
            ],
            [
                4,
                =>
                    @gp_object.honoka.setEmote('bikkuri')
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtSet(
                        '穂乃果<br>大変大変大変！'
                    )
            ],
            [
                4,
                =>
                    @unsetEmote()
                    @gp_object.umi.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '海未<br>一体どうしたというのですか、,<br>穂乃果'
                    )
            ],
            [
                4,
                =>
                    @gp_object.honoka.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>ラブライブの予選にエントリーした<br>私達みんなで作った曲なんだけど'
                    )
            ],
            [
                4,
                =>
                    @gp_object.kotori.setEmote('onpu')
                    @gp_object.kotori.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>snow halationのことだね。,<br>いい曲だよね。'
                    )
            ],
            [
                5,
                =>
                    @unsetEmote()
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>そう、,そのことなんだけど、,<br>そのsnow halationの<br>最後のほうでの演出、'
                    )
            ],
            [
                5,
                =>
                    @gp_object.honoka.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>舞台全体をオレンジ一色に<br>ライトアップする装置なんだけど・・・'
                    )
            ],
            [
                5,
                =>
                    @gp_object.honoka.setEmote('bikkuri')
                    @gp_object.honoka.scaleIn()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>ななななんと！,<br>その装置を作るのに『１００億円』も<br>かかるんだって！！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.umi.setEmote('bikkuri')
                    @gp_object.umi.scaleIn()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '海未<br>『１００億円』！？,<br>穂乃果、,それはどう考えても<br>おかしいですよ。'
                    )
            ],
            [
                5,
                =>
                    @gp_object.kotori.setEmote('bikkuri')
                    @gp_object.kotori.scaleIn()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>そうだよホノカチャン,<br>『１００億円』なんて、,<br>何かの間違いじゃない？'
                    )
            ],
            [
                4,
                =>
                    @unsetEmote()
                    @gp_sentence.txtEnd()
                    @gp_object.kotori.scaleOut()
                    @gp_object.honoka.scaleOut()
                    @gp_object.umi.scaleOut()
            ],
            [
                5,
                =>
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtSet(
                        '穂乃果<br>もうっ！,<br>何が何でも『１００億円』集めるの！,<br>集めるったら集めるの！'
                    )
            ],
            [
                4,
                =>
                    @gp_object.umi.setEmote('ase')
                    @gp_object.umi.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '海未<br>全く話を聞いていませんね。,<br>まあ、,仕方ないでしょう'
                    )
            ],
            [
                4,
                =>
                    @unsetEmote()
                    @gp_object.umi.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '海未<br>今回もまた、,<br>真姫のポケットマネーから<br>出ているという、'
                    )
            ],
            [
                4,
                =>
                    @gp_object.umi.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '海未<br>あの変なスロットマシンを<br>使うのでしょう？'
                    )
            ],
            [
                6,
                =>
                    @gp_object.kotori.setEmote('ase')
                    @gp_object.kotori.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>そうだね、,<br>あれ、,スロットマシンとは言っても、,<br>まさか屋上に<br>あんな巨大な装置があって'
                    )
            ],
            [
                5,
                =>
                    @unsetEmote()
                    @gp_object.kotori.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>空から降ってくるお菓子を<br>取って止めるなんて,<br>思わなかったよ。'
                    )
            ],
            [
                5,
                =>
                    @gp_object.kotori.setEmote('gabin')
                    @gp_object.kotori.randomShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>爆弾降ってくるし、、、'
                    )
            ],
            [
                5,
                =>
                    @unsetEmote()
                    @gp_object.kotori.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>ことりちゃんの気ぐるみは<br>可愛いんだけど、,<br>あの中暑くて暑くて、、'
                    )
            ],
            [
                3,
                =>
                    @gp_object.kotori.setEmote('ten')
                    @gp_sentence.txtEnd()
            ],
            [
                4,
                =>
                    @gp_object.kotori.setEmote('bikkuri')
                    @gp_object.kotori.tateShake2()
                    @gp_sentence.txtSet(
                        'ことり<br>大変だけど、,<br>私ホノカチャンのために頑張る！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.kotori.setEmote('bikkuri')
                    @gp_object.kotori.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>待っててね！,ホノカチャン！'
                    )
            ],
            [
                3,
                =>
                    @gp_sentence.txtEnd()
                    @gp_object.honoka.tateShake2()
                    @gp_object.honoka.setEmote('onpu')
            ],
            [
                5,
                =>
                    @unsetEmote()
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtSet(
                        '穂乃果<br>頑張ってね！,ことりちゃん！,<br>ファイトだよっ！'
                    )
            ],
            [
                0,
                =>
                    game.endStory()
            ]
        ]
        @startScene()
    story4thStart:()->
        @panorama = 'back_kanda'
        @addLoadFile([
            'images/back_kanda.png', 'images/face_nico.png', 'images/face_nozomi.png', 'images/face_eli.png',
            'sounds/bgm/bgm_chace.mp3'
        ])
        @cue = [
            [
                6,
                =>
                    @gp_sentence.txtSet(
                        'μ’ｓは２度目に出場した<br>ラブライブの予選を突破し、<br>A-RISEを公開処刑。<br>その勢いで優勝にまで至る。'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'その決戦のμ’ｓのパフォーマンスは<br>これまでかと注ぎ込んだ予算の影響で'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'とてもスクールアイドルが<br>やっているとは思えないような<br>クオリティであった。'
                    )
            ],
            [
                4,
                =>
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'そして、<br>3年生の卒業式が<br>終わったのも束の間、'
                    )
            ],
            [
                5,
                =>
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'μ’ｓのもとには<br>ラブライブ運営より<br>ニューヨークでのPV撮影の<br>依頼が届く。'
                    )
            ],
            [
                2,
                =>
                    @gp_object.playBgm('bgm_chace')
                    @gp_sentence.txtEnd()
                    @faceSet(@gp_object.nozomi, 165, 98)
                    @faceSet(@gp_object.nico, 10, 90)
                    @faceSet(@gp_object.eli, 330, 90)
            ],
            [
                4,
                =>
                    @gp_object.nico.setEmote('onpu')
                    @gp_object.nico.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>やったわ、,<br>私達もついに大人気アイドルね！'
                    )
            ],
            [
                5,
                =>
                    @unsetEmote()
                    @gp_object.nico.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>それにしてもお金の力って凄いわ！,<br>出すPVはどんどん<br>クオリティが上がっていって、'
                    )
            ],
            [
                6,
                =>
                    @gp_object.nico.setEmote('heart')
                    @gp_object.nico.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>豪華な衣装をたくさん着たり、,<br>大掛かりなセットを使ったり、,<br>花火を打ち上げてみたり、'
                    )
            ],
            [
                5,
                =>
                    @gp_object.nico.setEmote('onpu')
                    @gp_object.nico.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>果てには空港をジャックして,<br>飛行機をラッピングしたり・・・'
                    )
            ],
            [
                6,
                =>
                    @gp_object.eli.setEmote('onpu')
                    @gp_object.eli.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '絵里<br>まったくハラショーだわ。,<br>ラブライブに優勝して、,<br>ついに私達も卒業かと思ったら'
                    )
            ],
            [
                5,
                =>
                    @gp_object.eli.setEmote('heart')
                    @gp_object.eli.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '絵里<br>今度はニューヨークで<br>PV撮影ですって！,<br>いまだに夢を見ているみたいだわ。'
                    )
            ],
            [
                5,
                =>
                    @gp_object.nozomi.setEmote('bikkuri')
                    @gp_object.nozomi.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '希<br>それだけやないでエリチ。,<br>見える！,うちには見えるんや、,未来が！'
                    )
            ],
            [
                7,
                =>
                    @unsetEmote()
                    @gp_object.nozomi.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '希<br>この後日本中の<br>スクールアイドルを集めて、,<br>秋葉原の歩行者天国を<br>開放して,ライブをするんや！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.nozomi.setEmote('bikkuri')
                    @gp_object.nozomi.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '希<br>更に、,うちらのファイナルライブを,<br>東京ドームですることになるんやで！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.eli.setEmote('ase')
                    @gp_object.eli.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '絵里<br>ちょっと希、,<br>いくらなんでもそれは、,、,<br>妄想が過ぎるわよ'
                    )
            ],
            [
                4,
                =>
                    @gp_object.nico.setEmote('bikkuri')
                    @gp_object.nico.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>いや、,絵里、,<br>それありえなくもないわ。'
                    )
            ],
            [
                5,
                =>
                    @gp_object.nico.setEmote('bikkuri')
                    @gp_object.nico.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>今からそのために<br>必要な資金を集めておかないと！,<br>大変なことになるわよ！'
                    )
            ],
            [
                6,
                =>
                    @unsetEmote()
                    @gp_object.nico.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>実は既に,<br>海未のゴーストライターである<br>畑亜貴さんに依頼して、,<br>次のシングル３曲'
                    )
            ],
            [
                8,
                =>
                    @gp_object.nico.setEmote('heart')
                    @gp_object.nico.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>Angelic Angel、,<br>SUNNY DAY SONG、,<br>僕たちはひとつの光、,っていう<br>曲の歌詞が,既にできているのよ！'
                    )
            ],
            [
                3,
                =>
                    @gp_object.eli.setEmote('ten')
                    @gp_sentence.txtEnd()
            ],
            [
                6,
                =>
                    @gp_object.eli.setEmote('ase')
                    @gp_object.eli.randomShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '絵里<br>何ちょっとにこ、,<br>何を言っているのかわからないわ。,<br>ゴーストライター？,ハターキ？'
                    )
            ],
            [
                4,
                =>
                    @unsetEmote()
                    @gp_object.eli.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '絵里<br>何それ初めて聞いたわ。,<br>ハラショーすぎるわ。'
                    )
            ],
            [
                6,
                =>
                    @gp_object.nozomi.setEmote('onpu')
                    @gp_object.nozomi.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '希<br>さすがにこっち、,<br>話が早くて助かるやん。,<br>そう、,そのためには金が必要なんや！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.nozomi.setEmote('bikkuri')
                    @gp_object.nozomi.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '希<br>もっともっと、,金が！,<br>ざっと見て『１００兆円』は必要やで！！！'
                    )
            ],
            [
                3,
                =>
                    @gp_object.eli.setEmote('ten')
                    @gp_sentence.txtEnd()
            ],
            [
                5,
                =>
                    @gp_object.eli.setEmote('gabin')
                    @gp_object.eli.randomShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '絵里<br>ちょっと待って２人共、,<br>何もかもがおかしいわ？,<br>『１００兆円』！？'
                    )
            ],
            [
                6,
                =>
                    @unsetEmote()
                    @gp_object.eli.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '絵里<br>デタラメにも程があるわ、,<br>それにさっきから聞いてて、,<br>突っ込みどころ満載よ？'
                    )
            ],
            [
                4,
                =>
                    @gp_object.nico.setEmote('onpu')
                    @gp_object.nico.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>そういうことだから、,<br>頑張ってね！,『１００兆円』！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.nico.setEmote('bikkuri')
                    @gp_object.nico.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>ラストまであともう一踏ん張り！,<br>おやつの落下速度は<br>更に上がっていくわ！'
                    )
            ],
            [
                6,
                =>
                    @gp_object.nozomi.setEmote('bikkuri')
                    @gp_object.nozomi.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '希<br>コツはスキルを上手く駆使して,<br>おやつを取りやすくすることやで！,<br>ぎょーさん頑張ってな！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.eli.setEmote('ase')
                    @gp_object.eli.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '絵里<br>それ誰に言ってるの？,<br>もう何でもいいわ。,ハラショーね。'
                    )
            ],
            [
                0,
                =>
                    game.endStory()
            ]
        ]
        @startScene()
    edStart:()->
        @panorama = 'back_busitu'
        @addLoadFile(['images/back_busitu.png', 'images/back_stage.png', 'images/face_honoka.png', 'images/face_kotori.png',
            'images/face_umi.png', 'images/face_maki.png', 'images/face_rin.png', 'images/face_hanayo.png',
            'images/face_nico.png', 'images/face_nozomi.png', 'images/face_eli.png',
            'sounds/bgm/bgm_tanosii.mp3', 'sounds/bgm/bgm_sugisarisi.mp3', 'sounds/bgm/bgm_gyakkyou.mp3'
        ])
        @cue = [
            #BGM楽しい部活
            [
                1,
                =>
                    @gp_object.playBgm('bgm_tanosii')
                    @faceSet(@gp_object.honoka, 80, 90)
                    @faceSet(@gp_object.kotori, 250, 90)
            ],
            [
                4,
                =>
                    @gp_object.honoka.setEmote('onpu')
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtSet(
                        '穂乃果<br>すごいよすごいよ！,<br>１００兆円だよ！,１００兆円！'
                    )
            ],
            [
                7,
                =>
                    @gp_object.honoka.setEmote('heart')
                    @gp_object.honoka.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>私達最強のスクールアイドルだよ！,<br>すごいね！,金の力って、,<br>お金最高！,お金万歳！！'
                    )
            ],
            [
                4,
                =>
                    @gp_object.kotori.setEmote('heart')
                    @gp_object.kotori.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>そうだね！,ホノカチャン！'
                    )
            ],
            [
                6,
                =>
                    @gp_object.honoka.setEmote('onpu')
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>最終的には私達<br>何もしてなかったね！,<br>歌だって代理の声優さんたちが<br>やってくれたし！'
                    )
            ],
            [
                7
                =>
                    @gp_object.honoka.setEmote('heart')
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>新田恵海さん、,<br>私の声そっくりだったよ！,<br>内田彩さんは<br>ことりちゃん以上に<br>ことりちゃんだったよ！'
                    )
            ],
            [
                4,
                =>
                    @gp_object.kotori.setEmote('bikkuri')
                    @gp_object.kotori.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>ホノカチャン！,ホノカチャン！'
                    )
            ],
            [
                4,
                =>
                    @gp_object.honoka.setEmote('bikkuri')
                    @gp_object.honoka.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>お、,ことりちゃんも興奮気味だね！'
                    )
            ],
            [
                7,
                =>
                    @gp_object.honoka.setEmote('onpu')
                    @gp_object.honoka.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>サンライズさんが作ってくれた<br>私達のアニメ、,感動的だったね！,<br>穂乃果感動して<br>何回も泣いちゃったよ！'
                    )
            ],
            #BGMフェードアウト
            [
                5,
                =>
                    @gp_object.kotori.setEmote('bikkuri')
                    @gp_object.kotori.scaleIn()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>ホノカチャン！,起きて！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.honoka.setEmote('hatena')
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>何？,私なら起きてるよ？'
                    )
            ],
            [
                5,
                =>
                    @gp_object.kotori.setEmote('bikkuri')
                    @gp_object.kotori.randomShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>ホノカチャン！,起きて！,<br>ライブ始まるよ！,ホノカチャン！！'
                    )
            ],
            [
                2,
                =>
                    @unsetEmote()
                    @gp_sentence.txtEnd()
                    @gp_object.kotori.scaleOut()
                    @panoramaChangeRect()
                    @gp_object.honoka.opacity = 0
                    @gp_object.kotori.opacity = 0
            ],
            [
                2,
                =>
                    @panoramaChange('back_stage')
                    @gp_object.honoka.opacity = 1
                    @gp_object.kotori.opacity = 1
            ],
            [
                5,
                =>
                    @gp_object.honoka.setEmote('hatena')
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>あれ・・・？,私・・・？,ここは？'
                    )
            ],
            #BGM過ぎ去りし日々
            [
                5,
                =>
                    @gp_object.playBgm('bgm_sugisarisi')
                    @gp_object.kotori.setEmote('bikkuri')
                    @gp_object.kotori.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>そろそろ始まるよ！,<br>私達のファイナルライブ！！'
                    )
            ],
            [
                6,
                =>
                    @gp_object.honoka.setEmote('hatena')
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>ファイナルライブ？,<br>そんなのお金の力で<br>代理の人たちがやってくれるよ？'
                    )
            ],
            [
                4,
                =>
                    @unsetEmote()
                    @gp_object.honoka.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>CGだって凄い<br>豪華なのがあるんだよ？'
                    )
            ],
            [
                5,
                =>
                    @gp_object.kotori.setEmote('bikkuri')
                    @gp_object.kotori.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>何を寝ぼけているの！？,<br>お金？,そんなのないよ！？'
                    )
            ],
            [
                6,
                =>
                    @unsetEmote()
                    @gp_object.kotori.scale()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>代理の人なんていないよ！,<br>μ’ｓは私達９人で<br>頑張ってここまで<br>来たんじゃない！'
                    )
            ],
            #BGMフェードアウト
            [
                4,
                =>
                    @gp_object.honoka.setEmote('bikkuri')
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>！？,<br>！！！！！？？？？？？？'
                    )
            ],
            [
                5,
                =>
                    @gp_object.honoka.setEmote('gabin')
                    @gp_object.honoka.randomShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>あーーーーーーーーーー<br>ーーーーーーーーーっ！！！！！'
                    )
            ],
            [
                2,
                =>
                    @gp_object.playBgm('bgm_gyakkyou')
                    @gp_sentence.txtEnd()
                    @unsetEmote()
                    @faceSet(@gp_object.rin, 180, 0)
                    @faceSet(@gp_object.hanayo, 50, 0)
                    @faceSet(@gp_object.maki, 300, 0)
                    @faceSet(@gp_object.honoka, 180, 90, true)
                    @faceSet(@gp_object.kotori, 300, 90, true)
                    @faceSet(@gp_object.umi, 50, 90)
                    @faceSet(@gp_object.nozomi, 170, 190)
                    @faceSet(@gp_object.nico, 40, 190)
                    @faceSet(@gp_object.eli, 300, 190)
                    @gp_object.rin.scaleChange(0.7)
                    @gp_object.hanayo.scaleChange(0.7)
                    @gp_object.maki.scaleChange(0.7)
                    @gp_object.honoka.scaleChange(0.7)
                    @gp_object.kotori.scaleChange(0.7)
                    @gp_object.umi.scaleChange(0.7)
                    @gp_object.nozomi.scaleChange(0.7)
                    @gp_object.nico.scaleChange(0.7)
                    @gp_object.eli.scaleChange(0.7)
            ],
            #BGM逆境からのスタート
            [
                4,
                =>
                    @gp_object.umi.setEmote('ase')
                    @gp_object.umi.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '海未<br>なんだ、,やっと気付いたのですね？'
                    )
            ],
            [
                4,
                =>
                    @gp_object.rin.setEmote('onpu')
                    @gp_object.rin.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '凛<br>とんだお寝坊さんだにゃ'
                    )
            ],
            [
                4,
                =>
                    @gp_object.nozomi.setEmote('onpu')
                    @gp_object.nozomi.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '希<br>スピリチュアルな夢でも見とったん？'
                    )
            ],
            [
                4,
                =>
                    @gp_object.maki.setEmote('ase')
                    @gp_object.maki.rotateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '真姫<br>イミワカンナイ'
                    )
            ],
            [
                4,
                =>
                    @gp_object.eli.setEmote('ase')
                    @gp_object.eli.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '絵里<br>ハラショーな夢だわ'
                    )
            ],
            [
                4,
                =>
                    @gp_object.hanayo.setEmote('bikkuri')
                    @gp_object.hanayo.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '花陽<br>そろそろライブ,始まっちゃいますよ？'
                    )
            ],
            [
                4,
                =>
                    @gp_object.nico.setEmote('bikkuri')
                    @gp_object.nico.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>見せてやるわよ、,<br>私達の１年間の集大成！！'
                    )
            ],
            [
                4
                =>
                    @gp_object.kotori.setEmote('bikkuri')
                    @gp_object.kotori.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>いくよ、,ホノカチャン！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.honoka.setEmote('bikkuri')
                    @gp_object.honoka.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>うん、,ごめんね！,<br>今完全に目が覚めたよ！'
                    )
            ],
            [
                5,
                =>
                    @unsetEmote()
                    @gp_object.honoka.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>そう、,私たちは、,<br>お金の力なんかじゃない！'
                    )
            ],
            [
                7,
                =>
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>私達９人で、,<br>高校生活という<br>限られた時間の中で,<br>精一杯頑張って<br>ここまで来たんだから！'
                    )
            ],
            [
                5,
                =>
                    @gp_object.honoka.setEmote('bikkuri')
                    @gp_object.honoka.tateShake2()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>行くよ！,ファイナル！,せーのっ'
                    )
            ],
            [
                2,
                =>
                    @unsetEmote()
                    @gp_object.honoka.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '穂乃果<br>１！'
                    )
            ],
            [
                2,
                =>
                    @gp_object.kotori.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'ことり<br>２！'
                    )
            ],
            [
                2,
                =>
                    @gp_object.umi.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '海未<br>３！'
                    )
            ],
            [
                2,
                =>
                    @gp_object.maki.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '真姫<br>４！'
                    )
            ],
            [
                2,
                =>
                    @gp_object.rin.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '凛<br>５！'
                    )
            ],
            [
                2,
                =>
                    @gp_object.hanayo.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '花陽<br>６！'
                    )
            ],
            [
                2,
                =>
                    @gp_object.nico.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        'にこ<br>７！'
                    )
            ],
            [
                2,
                =>
                    @gp_object.nozomi.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '希<br>８！'
                    )
            ],
            [
                2,
                =>
                    @gp_object.eli.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '絵里<br>９！'
                    )
            ],
            [
                2,
                =>
                    @gp_sentence.txtEnd()
                    console.log('俺「１０！！」')
            ],
            [
                6,
                =>
                    @gp_object.honoka.tateShake()
                    @gp_object.kotori.tateShake()
                    @gp_object.umi.tateShake()
                    @gp_object.maki.tateShake()
                    @gp_object.rin.tateShake()
                    @gp_object.hanayo.tateShake()
                    @gp_object.nico.tateShake()
                    @gp_object.nozomi.tateShake()
                    @gp_object.eli.tateShake()
                    @gp_sentence.txtEnd()
                    @gp_sentence.txtSet(
                        '全員<br>μ’ｓ、,,ミュージック、,,スタート！！'
                    )
            ],
            [
                0,
                =>
                    game.endStory()
            ]
        ]
        @startScene()
